version: '3.8'

services:
  node-app:
    build: 
      context: ./node-app
    container_name: node-app
    ports:
      - "3000:3000"
    networks:
      - web-network
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
